### PR TITLE
Update readme with required sections

### PR DESCRIPTION
**Pull request by semioticrobotic**
This pull request adds a few new sections to the project README. It does so primarily to test automations associated with the DCO bot.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
Nothing urgent here, @gsmith-sas, but since this PR does actually add a few sections and specifications to the README, I wanted to give you the opportunity to have a look.

**Review by gsmith-sas — CHANGES_REQUESTED** [review]
Rather than move the links to the project's documentation to a separate **_Additional resources_** section, I'd like to keep it with the project info (now under the **_Overview_** section).  We moved virtually all of the project's documentation to the Help Center and want to make sure users know where to find it.  

So, I'm asking that we move the new **_Contributing_** and **_License_** sections to after the proposed **_Additional resources_** section an remove the **_Additional resources_** section header.

**Comment by semioticrobotic** [comment]
Sure thing, @gsmith-sas. Makes sense to me.

**Review by gsmith-sas — APPROVED** [review]
Thanks for the changes.  LGTM.

**Pull request merged**
